# #####################################################################
# Automatically generated by qmake (2.01a) ?? ????? 19 23:43:43 2010
# #####################################################################
QT += sql \
    testlib \
    webkit
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    dbs \
    edit \
    report \
    settings
INCLUDEPATH += . \
    dbs \
    edit \
    report \
    settings

# Input
HEADERS += aboutdialog.h \
    connect.h \
    dbsdialog.h \
    helpbrowser.h \
    logo_widget.h \
    mainwindow.h \
    os_model.h \
    selectuserdialog.h \
    statusbar_label.h \
    styles.h \
    treewidget.h \
    tv_delegate.h \
    ui_test.h \
    ui_testform.h \
    update_model.h \
    user.h \
    dbs/dbeditdialog.h \
    dbs/dbsettingsini.h \
    edit/comp_model.h \
    edit/gcomp_model.h \
    edit/gcomps.h \
    edit/gprogs.h \
    edit/gprogs_model.h \
    edit/hiddenlistdialog.h \
    edit/listsdialog.h \
    edit/prog.h \
    edit/prog_model.h \
    report/browser.h \
    report/mkreport.h \
    report/reportstreewidget.h \
    settings/usersdialog.h \
    print/printtableview.h \
    print/printdialog.h
FORMS += aboutdialog.ui \
    dbsdialog.ui \
    helpbrowser.ui \
    mainwindow.ui \
    selectuserdialog.ui \
    dbs/dbeditdialog.ui \
    edit/gcomps.ui \
    edit/gprogs.ui \
    edit/gprogs_.ui \
    edit/hiddenlistdialog.ui \
    edit/listsdialog.ui \
    report/browser.ui \
    settings/usersdialog.ui \
    print/printdialog.ui
SOURCES += aboutdialog.cpp \
    dbsdialog.cpp \
    helpbrowser.cpp \
    logo_widget.cpp \
    main.cpp \
    mainwindow.cpp \
    os_model.cpp \
    selectuserdialog.cpp \
    statusbar_label.cpp \
    treewidget.cpp \
    tv_delegate.cpp \
    update_model.cpp \
    dbs/dbeditdialog.cpp \
    dbs/dbsettingsini.cpp \
    edit/comp_model.cpp \
    edit/gcomp_model.cpp \
    edit/gcomps.cpp \
    edit/gprogs.cpp \
    edit/gprogs_model.cpp \
    edit/hiddenlistdialog.cpp \
    edit/listsdialog.cpp \
    edit/prog_model.cpp \
    edit/prog_model_.cpp \
    report/browser.cpp \
    report/reportstreewidget.cpp \
    settings/usersdialog.cpp \
    print/printtableview.cpp \
    print/printdialog.cpp
RESOURCES += res.qrc
TRANSLATIONS += admin_en.ts \
    qt_ru.ts
