#############################################################################
# Makefile for building: Admin_test
# Generated by qmake (2.01a) (Qt 4.6.2) on: ?? ????? 19 23:56:49 2010
# Project:  Admin_test.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile Admin_test.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_TESTLIB_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=core2 -O2 -pipe -msse4.1 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=core2 -O2 -pipe -msse4.1 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtTest -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -Idbs -Iedit -Ireport -Isettings -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib64/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtWebKit -L/usr/lib64 -L/usr/lib64/qt4 -L/usr/X11R6/lib -lphonon -lQtNetwork -lQtTest -lQtSql -L/usr/lib64/mysql -lQtGui -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = aboutdialog.cpp \
		dbsdialog.cpp \
		helpbrowser.cpp \
		logo_widget.cpp \
		main.cpp \
		mainwindow.cpp \
		os_model.cpp \
		selectuserdialog.cpp \
		statusbar_label.cpp \
		treewidget.cpp \
		tv_delegate.cpp \
		update_model.cpp \
		dbs/dbeditdialog.cpp \
		dbs/dbsettingsini.cpp \
		edit/comp_model.cpp \
		edit/gcomp_model.cpp \
		edit/gcomps.cpp \
		edit/gprogs.cpp \
		edit/gprogs_model.cpp \
		edit/hiddenlistdialog.cpp \
		edit/listsdialog.cpp \
		edit/prog_model.cpp \
		edit/prog_model_.cpp \
		report/browser.cpp \
		report/reportstreewidget.cpp \
		settings/usersdialog.cpp \
		print/printtableview.cpp \
		print/printdialog.cpp moc_aboutdialog.cpp \
		moc_dbsdialog.cpp \
		moc_helpbrowser.cpp \
		moc_logo_widget.cpp \
		moc_mainwindow.cpp \
		moc_selectuserdialog.cpp \
		moc_statusbar_label.cpp \
		moc_tv_delegate.cpp \
		moc_dbeditdialog.cpp \
		moc_gcomps.cpp \
		moc_gprogs.cpp \
		moc_hiddenlistdialog.cpp \
		moc_listsdialog.cpp \
		moc_browser.cpp \
		moc_usersdialog.cpp \
		moc_printdialog.cpp \
		qrc_res.cpp
OBJECTS       = aboutdialog.o \
		dbsdialog.o \
		helpbrowser.o \
		logo_widget.o \
		main.o \
		mainwindow.o \
		os_model.o \
		selectuserdialog.o \
		statusbar_label.o \
		treewidget.o \
		tv_delegate.o \
		update_model.o \
		dbeditdialog.o \
		dbsettingsini.o \
		comp_model.o \
		gcomp_model.o \
		gcomps.o \
		gprogs.o \
		gprogs_model.o \
		hiddenlistdialog.o \
		listsdialog.o \
		prog_model.o \
		prog_model_.o \
		browser.o \
		reportstreewidget.o \
		usersdialog.o \
		printtableview.o \
		printdialog.o \
		moc_aboutdialog.o \
		moc_dbsdialog.o \
		moc_helpbrowser.o \
		moc_logo_widget.o \
		moc_mainwindow.o \
		moc_selectuserdialog.o \
		moc_statusbar_label.o \
		moc_tv_delegate.o \
		moc_dbeditdialog.o \
		moc_gcomps.o \
		moc_gprogs.o \
		moc_hiddenlistdialog.o \
		moc_listsdialog.o \
		moc_browser.o \
		moc_usersdialog.o \
		moc_printdialog.o \
		qrc_res.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Admin_test.pro
QMAKE_TARGET  = Admin_test
DESTDIR       = 
TARGET        = Admin_test

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_aboutdialog.h ui_dbsdialog.h ui_helpbrowser.h ui_mainwindow.h ui_selectuserdialog.h ui_dbeditdialog.h ui_gcomps.h ui_gprogs.h ui_gprogs_.h ui_hiddenlistdialog.h ui_listsdialog.h ui_browser.h ui_usersdialog.h ui_printdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Admin_test.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtWebKit.prl \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtCore.prl \
		/usr/lib64/qt4/libQtNetwork.prl \
		/usr/lib64/qt4/libQtTest.prl \
		/usr/lib64/qt4/libQtSql.prl
	$(QMAKE) -unix -o Makefile Admin_test.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtWebKit.prl:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtCore.prl:
/usr/lib64/qt4/libQtNetwork.prl:
/usr/lib64/qt4/libQtTest.prl:
/usr/lib64/qt4/libQtSql.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Admin_test.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Admin_test1.0.0 || $(MKDIR) .tmp/Admin_test1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Admin_test1.0.0/ && $(COPY_FILE) --parents aboutdialog.h connect.h dbsdialog.h helpbrowser.h logo_widget.h mainwindow.h os_model.h selectuserdialog.h statusbar_label.h styles.h treewidget.h tv_delegate.h ui_test.h ui_testform.h update_model.h user.h dbs/dbeditdialog.h dbs/dbsettingsini.h edit/comp_model.h edit/gcomp_model.h edit/gcomps.h edit/gprogs.h edit/gprogs_model.h edit/hiddenlistdialog.h edit/listsdialog.h edit/prog.h edit/prog_model.h report/browser.h report/mkreport.h report/reportstreewidget.h settings/usersdialog.h print/printtableview.h print/printdialog.h .tmp/Admin_test1.0.0/ && $(COPY_FILE) --parents res.qrc .tmp/Admin_test1.0.0/ && $(COPY_FILE) --parents aboutdialog.cpp dbsdialog.cpp helpbrowser.cpp logo_widget.cpp main.cpp mainwindow.cpp os_model.cpp selectuserdialog.cpp statusbar_label.cpp treewidget.cpp tv_delegate.cpp update_model.cpp dbs/dbeditdialog.cpp dbs/dbsettingsini.cpp edit/comp_model.cpp edit/gcomp_model.cpp edit/gcomps.cpp edit/gprogs.cpp edit/gprogs_model.cpp edit/hiddenlistdialog.cpp edit/listsdialog.cpp edit/prog_model.cpp edit/prog_model_.cpp report/browser.cpp report/reportstreewidget.cpp settings/usersdialog.cpp print/printtableview.cpp print/printdialog.cpp .tmp/Admin_test1.0.0/ && $(COPY_FILE) --parents aboutdialog.ui dbsdialog.ui helpbrowser.ui mainwindow.ui selectuserdialog.ui dbs/dbeditdialog.ui edit/gcomps.ui edit/gprogs.ui edit/gprogs_.ui edit/hiddenlistdialog.ui edit/listsdialog.ui report/browser.ui settings/usersdialog.ui print/printdialog.ui .tmp/Admin_test1.0.0/ && $(COPY_FILE) --parents admin_en.ts qt_ru.ts .tmp/Admin_test1.0.0/ && (cd `dirname .tmp/Admin_test1.0.0` && $(TAR) Admin_test1.0.0.tar Admin_test1.0.0 && $(COMPRESS) Admin_test1.0.0.tar) && $(MOVE) `dirname .tmp/Admin_test1.0.0`/Admin_test1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Admin_test1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_aboutdialog.cpp moc_dbsdialog.cpp moc_helpbrowser.cpp moc_logo_widget.cpp moc_mainwindow.cpp moc_selectuserdialog.cpp moc_statusbar_label.cpp moc_tv_delegate.cpp moc_dbeditdialog.cpp moc_gcomps.cpp moc_gprogs.cpp moc_hiddenlistdialog.cpp moc_listsdialog.cpp moc_browser.cpp moc_usersdialog.cpp moc_printdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_aboutdialog.cpp moc_dbsdialog.cpp moc_helpbrowser.cpp moc_logo_widget.cpp moc_mainwindow.cpp moc_selectuserdialog.cpp moc_statusbar_label.cpp moc_tv_delegate.cpp moc_dbeditdialog.cpp moc_gcomps.cpp moc_gprogs.cpp moc_hiddenlistdialog.cpp moc_listsdialog.cpp moc_browser.cpp moc_usersdialog.cpp moc_printdialog.cpp
moc_aboutdialog.cpp: logo_widget.h \
		aboutdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) aboutdialog.h -o moc_aboutdialog.cpp

moc_dbsdialog.cpp: logo_widget.h \
		dbs/dbeditdialog.h \
		dbs/dbsettingsini.h \
		dbsdialog.h \
		connect.h \
		user.h \
		selectuserdialog.h \
		styles.h \
		mainwindow.h \
		edit/gcomps.h \
		edit/comp_model.h \
		edit/gcomp_model.h \
		edit/gprogs.h \
		edit/prog_model.h \
		edit/gprogs_model.h \
		os_model.h \
		update_model.h \
		edit/listsdialog.h \
		edit/hiddenlistdialog.h \
		print/printtableview.h \
		print/printdialog.h \
		report/mkreport.h \
		report/browser.h \
		report/reportstreewidget.h \
		aboutdialog.h \
		treewidget.h \
		tv_delegate.h \
		settings/usersdialog.h \
		helpbrowser.h \
		dbsdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) dbsdialog.h -o moc_dbsdialog.cpp

moc_helpbrowser.cpp: styles.h \
		helpbrowser.h
	/usr/bin/moc $(DEFINES) $(INCPATH) helpbrowser.h -o moc_helpbrowser.cpp

moc_logo_widget.cpp: logo_widget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) logo_widget.h -o moc_logo_widget.cpp

moc_mainwindow.cpp: user.h \
		edit/gcomps.h \
		edit/comp_model.h \
		edit/gcomp_model.h \
		connect.h \
		styles.h \
		edit/gprogs.h \
		edit/prog_model.h \
		edit/gprogs_model.h \
		os_model.h \
		update_model.h \
		edit/listsdialog.h \
		edit/hiddenlistdialog.h \
		print/printtableview.h \
		print/printdialog.h \
		report/mkreport.h \
		report/browser.h \
		report/reportstreewidget.h \
		aboutdialog.h \
		logo_widget.h \
		treewidget.h \
		tv_delegate.h \
		settings/usersdialog.h \
		helpbrowser.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_selectuserdialog.cpp: connect.h \
		user.h \
		styles.h \
		mainwindow.h \
		edit/gcomps.h \
		edit/comp_model.h \
		edit/gcomp_model.h \
		edit/gprogs.h \
		edit/prog_model.h \
		edit/gprogs_model.h \
		os_model.h \
		update_model.h \
		edit/listsdialog.h \
		edit/hiddenlistdialog.h \
		print/printtableview.h \
		print/printdialog.h \
		report/mkreport.h \
		report/browser.h \
		report/reportstreewidget.h \
		aboutdialog.h \
		logo_widget.h \
		treewidget.h \
		tv_delegate.h \
		settings/usersdialog.h \
		helpbrowser.h \
		selectuserdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) selectuserdialog.h -o moc_selectuserdialog.cpp

moc_statusbar_label.cpp: statusbar_label.h
	/usr/bin/moc $(DEFINES) $(INCPATH) statusbar_label.h -o moc_statusbar_label.cpp

moc_tv_delegate.cpp: tv_delegate.h
	/usr/bin/moc $(DEFINES) $(INCPATH) tv_delegate.h -o moc_tv_delegate.cpp

moc_dbeditdialog.cpp: dbs/dbsettingsini.h \
		dbsdialog.h \
		logo_widget.h \
		dbs/dbeditdialog.h \
		styles.h \
		connect.h \
		user.h \
		selectuserdialog.h \
		mainwindow.h \
		edit/gcomps.h \
		edit/comp_model.h \
		edit/gcomp_model.h \
		edit/gprogs.h \
		edit/prog_model.h \
		edit/gprogs_model.h \
		os_model.h \
		update_model.h \
		edit/listsdialog.h \
		edit/hiddenlistdialog.h \
		print/printtableview.h \
		print/printdialog.h \
		report/mkreport.h \
		report/browser.h \
		report/reportstreewidget.h \
		aboutdialog.h \
		treewidget.h \
		tv_delegate.h \
		settings/usersdialog.h \
		helpbrowser.h \
		dbs/dbeditdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) dbs/dbeditdialog.h -o moc_dbeditdialog.cpp

moc_gcomps.cpp: edit/comp_model.h \
		edit/gcomp_model.h \
		connect.h \
		user.h \
		styles.h \
		edit/gcomps.h
	/usr/bin/moc $(DEFINES) $(INCPATH) edit/gcomps.h -o moc_gcomps.cpp

moc_gprogs.cpp: edit/prog_model.h \
		edit/gprogs_model.h \
		connect.h \
		user.h \
		styles.h \
		edit/gprogs.h
	/usr/bin/moc $(DEFINES) $(INCPATH) edit/gprogs.h -o moc_gprogs.cpp

moc_hiddenlistdialog.cpp: styles.h \
		edit/prog_model.h \
		connect.h \
		user.h \
		edit/hiddenlistdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) edit/hiddenlistdialog.h -o moc_hiddenlistdialog.cpp

moc_listsdialog.cpp: connect.h \
		user.h \
		edit/gcomp_model.h \
		edit/prog_model.h \
		styles.h \
		edit/listsdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) edit/listsdialog.h -o moc_listsdialog.cpp

moc_browser.cpp: styles.h \
		user.h \
		report/reportstreewidget.h \
		report/browser.h
	/usr/bin/moc $(DEFINES) $(INCPATH) report/browser.h -o moc_browser.cpp

moc_usersdialog.cpp: connect.h \
		user.h \
		styles.h \
		settings/usersdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) settings/usersdialog.h -o moc_usersdialog.cpp

moc_printdialog.cpp: print/printdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) print/printdialog.h -o moc_printdialog.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		GPL2 \
		images/splash.png \
		images/windows.png \
		images/linux.png \
		images/buttons/help.png \
		images/buttons/apply.png \
		images/buttons/add.png \
		images/buttons/reportbrowser.png \
		images/buttons/installdb.png \
		images/buttons/gcomps.png \
		images/buttons/go-home.png \
		images/buttons/refresh.png \
		images/buttons/edit.png \
		images/buttons/about.png \
		images/buttons/printer.png \
		images/buttons/connect.png \
		images/buttons/arrow-right.png \
		images/buttons/user-password.png \
		images/buttons/arrow-left.png \
		images/buttons/go-previous.png \
		images/buttons/cancel.png \
		images/buttons/exit.png \
		images/buttons/user-pass.png \
		images/buttons/help-contents.png \
		images/buttons/remove.png
	/usr/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_aboutdialog.h ui_dbsdialog.h ui_helpbrowser.h ui_mainwindow.h ui_selectuserdialog.h ui_dbeditdialog.h ui_gcomps.h ui_gprogs.h ui_gprogs_.h ui_hiddenlistdialog.h ui_listsdialog.h ui_browser.h ui_usersdialog.h ui_printdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_aboutdialog.h ui_dbsdialog.h ui_helpbrowser.h ui_mainwindow.h ui_selectuserdialog.h ui_dbeditdialog.h ui_gcomps.h ui_gprogs.h ui_gprogs_.h ui_hiddenlistdialog.h ui_listsdialog.h ui_browser.h ui_usersdialog.h ui_printdialog.h
ui_aboutdialog.h: aboutdialog.ui
	/usr/bin/uic aboutdialog.ui -o ui_aboutdialog.h

ui_dbsdialog.h: dbsdialog.ui
	/usr/bin/uic dbsdialog.ui -o ui_dbsdialog.h

ui_helpbrowser.h: helpbrowser.ui
	/usr/bin/uic helpbrowser.ui -o ui_helpbrowser.h

ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_selectuserdialog.h: selectuserdialog.ui
	/usr/bin/uic selectuserdialog.ui -o ui_selectuserdialog.h

ui_dbeditdialog.h: dbs/dbeditdialog.ui
	/usr/bin/uic dbs/dbeditdialog.ui -o ui_dbeditdialog.h

ui_gcomps.h: edit/gcomps.ui
	/usr/bin/uic edit/gcomps.ui -o ui_gcomps.h

ui_gprogs.h: edit/gprogs.ui
	/usr/bin/uic edit/gprogs.ui -o ui_gprogs.h

ui_gprogs_.h: edit/gprogs_.ui
	/usr/bin/uic edit/gprogs_.ui -o ui_gprogs_.h

ui_hiddenlistdialog.h: edit/hiddenlistdialog.ui
	/usr/bin/uic edit/hiddenlistdialog.ui -o ui_hiddenlistdialog.h

ui_listsdialog.h: edit/listsdialog.ui
	/usr/bin/uic edit/listsdialog.ui -o ui_listsdialog.h

ui_browser.h: report/browser.ui
	/usr/bin/uic report/browser.ui -o ui_browser.h

ui_usersdialog.h: settings/usersdialog.ui
	/usr/bin/uic settings/usersdialog.ui -o ui_usersdialog.h

ui_printdialog.h: print/printdialog.ui
	/usr/bin/uic print/printdialog.ui -o ui_printdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

aboutdialog.o: aboutdialog.cpp aboutdialog.h \
		logo_widget.h \
		ui_aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutdialog.o aboutdialog.cpp

dbsdialog.o: dbsdialog.cpp dbsdialog.h \
		logo_widget.h \
		dbs/dbeditdialog.h \
		dbs/dbsettingsini.h \
		styles.h \
		connect.h \
		user.h \
		selectuserdialog.h \
		mainwindow.h \
		edit/gcomps.h \
		edit/comp_model.h \
		edit/gcomp_model.h \
		edit/gprogs.h \
		edit/prog_model.h \
		edit/gprogs_model.h \
		os_model.h \
		update_model.h \
		edit/listsdialog.h \
		edit/hiddenlistdialog.h \
		print/printtableview.h \
		print/printdialog.h \
		report/mkreport.h \
		report/browser.h \
		report/reportstreewidget.h \
		aboutdialog.h \
		treewidget.h \
		tv_delegate.h \
		settings/usersdialog.h \
		helpbrowser.h \
		ui_dbsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbsdialog.o dbsdialog.cpp

helpbrowser.o: helpbrowser.cpp helpbrowser.h \
		styles.h \
		ui_helpbrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpbrowser.o helpbrowser.cpp

logo_widget.o: logo_widget.cpp logo_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logo_widget.o logo_widget.cpp

main.o: main.cpp dbsdialog.h \
		logo_widget.h \
		dbs/dbeditdialog.h \
		dbs/dbsettingsini.h \
		styles.h \
		connect.h \
		user.h \
		selectuserdialog.h \
		mainwindow.h \
		edit/gcomps.h \
		edit/comp_model.h \
		edit/gcomp_model.h \
		edit/gprogs.h \
		edit/prog_model.h \
		edit/gprogs_model.h \
		os_model.h \
		update_model.h \
		edit/listsdialog.h \
		edit/hiddenlistdialog.h \
		print/printtableview.h \
		print/printdialog.h \
		report/mkreport.h \
		report/browser.h \
		report/reportstreewidget.h \
		aboutdialog.h \
		treewidget.h \
		tv_delegate.h \
		settings/usersdialog.h \
		helpbrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		user.h \
		edit/gcomps.h \
		edit/comp_model.h \
		edit/gcomp_model.h \
		connect.h \
		styles.h \
		edit/gprogs.h \
		edit/prog_model.h \
		edit/gprogs_model.h \
		os_model.h \
		update_model.h \
		edit/listsdialog.h \
		edit/hiddenlistdialog.h \
		print/printtableview.h \
		print/printdialog.h \
		report/mkreport.h \
		report/browser.h \
		report/reportstreewidget.h \
		aboutdialog.h \
		logo_widget.h \
		treewidget.h \
		tv_delegate.h \
		settings/usersdialog.h \
		helpbrowser.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

os_model.o: os_model.cpp os_model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o os_model.o os_model.cpp

selectuserdialog.o: selectuserdialog.cpp selectuserdialog.h \
		connect.h \
		user.h \
		styles.h \
		mainwindow.h \
		edit/gcomps.h \
		edit/comp_model.h \
		edit/gcomp_model.h \
		edit/gprogs.h \
		edit/prog_model.h \
		edit/gprogs_model.h \
		os_model.h \
		update_model.h \
		edit/listsdialog.h \
		edit/hiddenlistdialog.h \
		print/printtableview.h \
		print/printdialog.h \
		report/mkreport.h \
		report/browser.h \
		report/reportstreewidget.h \
		aboutdialog.h \
		logo_widget.h \
		treewidget.h \
		tv_delegate.h \
		settings/usersdialog.h \
		helpbrowser.h \
		ui_selectuserdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o selectuserdialog.o selectuserdialog.cpp

statusbar_label.o: statusbar_label.cpp statusbar_label.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statusbar_label.o statusbar_label.cpp

treewidget.o: treewidget.cpp treewidget.h \
		connect.h \
		user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o treewidget.o treewidget.cpp

tv_delegate.o: tv_delegate.cpp tv_delegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tv_delegate.o tv_delegate.cpp

update_model.o: update_model.cpp update_model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o update_model.o update_model.cpp

dbeditdialog.o: dbs/dbeditdialog.cpp dbs/dbeditdialog.h \
		dbs/dbsettingsini.h \
		dbsdialog.h \
		logo_widget.h \
		connect.h \
		user.h \
		selectuserdialog.h \
		styles.h \
		mainwindow.h \
		edit/gcomps.h \
		edit/comp_model.h \
		edit/gcomp_model.h \
		edit/gprogs.h \
		edit/prog_model.h \
		edit/gprogs_model.h \
		os_model.h \
		update_model.h \
		edit/listsdialog.h \
		edit/hiddenlistdialog.h \
		print/printtableview.h \
		print/printdialog.h \
		report/mkreport.h \
		report/browser.h \
		report/reportstreewidget.h \
		aboutdialog.h \
		treewidget.h \
		tv_delegate.h \
		settings/usersdialog.h \
		helpbrowser.h \
		ui_dbeditdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbeditdialog.o dbs/dbeditdialog.cpp

dbsettingsini.o: dbs/dbsettingsini.cpp dbs/dbsettingsini.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbsettingsini.o dbs/dbsettingsini.cpp

comp_model.o: edit/comp_model.cpp edit/comp_model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o comp_model.o edit/comp_model.cpp

gcomp_model.o: edit/gcomp_model.cpp edit/gcomp_model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gcomp_model.o edit/gcomp_model.cpp

gcomps.o: edit/gcomps.cpp edit/gcomps.h \
		edit/comp_model.h \
		edit/gcomp_model.h \
		connect.h \
		user.h \
		styles.h \
		ui_gcomps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gcomps.o edit/gcomps.cpp

gprogs.o: edit/gprogs.cpp edit/gprogs.h \
		edit/prog_model.h \
		edit/gprogs_model.h \
		connect.h \
		user.h \
		styles.h \
		ui_gprogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gprogs.o edit/gprogs.cpp

gprogs_model.o: edit/gprogs_model.cpp edit/gprogs_model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gprogs_model.o edit/gprogs_model.cpp

hiddenlistdialog.o: edit/hiddenlistdialog.cpp edit/hiddenlistdialog.h \
		styles.h \
		edit/prog_model.h \
		connect.h \
		user.h \
		ui_hiddenlistdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hiddenlistdialog.o edit/hiddenlistdialog.cpp

listsdialog.o: edit/listsdialog.cpp edit/listsdialog.h \
		connect.h \
		user.h \
		edit/gcomp_model.h \
		edit/prog_model.h \
		styles.h \
		ui_listsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o listsdialog.o edit/listsdialog.cpp

prog_model.o: edit/prog_model.cpp edit/prog_model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prog_model.o edit/prog_model.cpp

prog_model_.o: edit/prog_model_.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prog_model_.o edit/prog_model_.cpp

browser.o: report/browser.cpp report/browser.h \
		styles.h \
		user.h \
		report/reportstreewidget.h \
		ui_browser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o browser.o report/browser.cpp

reportstreewidget.o: report/reportstreewidget.cpp report/reportstreewidget.h \
		user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reportstreewidget.o report/reportstreewidget.cpp

usersdialog.o: settings/usersdialog.cpp settings/usersdialog.h \
		connect.h \
		user.h \
		styles.h \
		ui_usersdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usersdialog.o settings/usersdialog.cpp

printtableview.o: print/printtableview.cpp print/printtableview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o printtableview.o print/printtableview.cpp

printdialog.o: print/printdialog.cpp print/printdialog.h \
		ui_printdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o printdialog.o print/printdialog.cpp

moc_aboutdialog.o: moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutdialog.o moc_aboutdialog.cpp

moc_dbsdialog.o: moc_dbsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dbsdialog.o moc_dbsdialog.cpp

moc_helpbrowser.o: moc_helpbrowser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_helpbrowser.o moc_helpbrowser.cpp

moc_logo_widget.o: moc_logo_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logo_widget.o moc_logo_widget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_selectuserdialog.o: moc_selectuserdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_selectuserdialog.o moc_selectuserdialog.cpp

moc_statusbar_label.o: moc_statusbar_label.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_statusbar_label.o moc_statusbar_label.cpp

moc_tv_delegate.o: moc_tv_delegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tv_delegate.o moc_tv_delegate.cpp

moc_dbeditdialog.o: moc_dbeditdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dbeditdialog.o moc_dbeditdialog.cpp

moc_gcomps.o: moc_gcomps.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gcomps.o moc_gcomps.cpp

moc_gprogs.o: moc_gprogs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gprogs.o moc_gprogs.cpp

moc_hiddenlistdialog.o: moc_hiddenlistdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hiddenlistdialog.o moc_hiddenlistdialog.cpp

moc_listsdialog.o: moc_listsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_listsdialog.o moc_listsdialog.cpp

moc_browser.o: moc_browser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_browser.o moc_browser.cpp

moc_usersdialog.o: moc_usersdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_usersdialog.o moc_usersdialog.cpp

moc_printdialog.o: moc_printdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_printdialog.o moc_printdialog.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

